config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"

  resources :genres, only: %i[index show]
  resources :lists, only: %i[show new create index edit update destroy] do
    resources :list_items, only: %i[create destroy update]
    resources :genre_connections, only: %i[create destroy update]
  end
  resources :titles, only: %i[index show new create] do
    resources :reviews, only: %i[create update destroy]
    resources :list_items, only: %i[create] do
      collection do
        post 'add_to_watchlist'
        post 'add_to_ratings_list'
      end
    end
  end
  resources :list_items, only: %i[new create destroy]

  get '/users/:username/followers', to: 'pages#followers', as: :followers
  get '/users/:username/following', to: 'users#following', as: :following
  get '/users/:username/follow', to: 'users#follow', as: :follow_user
  get '/users/:username/unfollow', to: 'users#unfollow', as: :unfollow_user

  get '/users/:username/edit', to: 'users#edit', as: :edit_user
  patch '/users/:username', to: 'users#update', as: :update_user

  get '/users/:username', to: 'users#show', as: :user
  get '/users/:username/lists', to: 'users#lists', as: 'user_lists'

  post 'add_to_watchlist', to: 'list_items#add_to_watchlist', as: :add_to_watchlist

  # Likes
  get '/reviews/:review/like_review', to: 'reviews#like_review', as: :like_review
  get '/reviews/:review/unlike_review', to: 'reviews#unlike_review', as: :unlike_review

  resources :people, only: %i[show]
  resources :services, only: %i[index show new create]
  resources :comments, only: [:create]

  get "up" => "rails/health#show", as: :rails_health_check

  get '/popular', to: 'titles#popular', as: :popular_titles
  get 'search', to: 'search#index', as: 'search'
  get 'movies', to: 'titles#movies', as: 'movies'
  get 'tv_shows', to: 'titles#tv_shows', as: 'tv_shows'
  get '/activity', to: 'pages#activity', as: :activity
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_items, dependent: :destroy
  has_many :titles, through: :list_items
  has_many :genre_connections, dependent: :destroy
  has_many :genres, through: :genre_connections

  validates :name, presence: true

  accepts_nested_attributes_for :genre_connections, allow_destroy: true, reject_if: :all_blank
  acts_as_favoritable

  def activity_string
    time_minutes = (Time.now - created_at) / 60
    if time_minutes <= 60
      "— #{time_minutes.round} minutes ago"
    elsif time_minutes > 60 && time_minutes < 1440
      time_hours = (time_minutes / 60).round
      "— #{time_hours} #{time_hours == 1 ? 'hour' : 'hours'} ago"
    else
      "— #{created_at.strftime('%b %d, %Y')}"
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lists = List.where.not(name: ['Watchlist'])
    @genres = Genre.where.not(cover_url: nil)
  end

  def show
    @list = List.includes(:user).find(params[:id])
      @list_items = if @list.name == 'Watchlist' || @list.name == 'Ratings'
                      @list.list_items.order(created_at: :desc)
                    else
                      @list.list_items.order(:rank)
                    end

    # @titles = @list_items.map {|list_item| list_item.title }
    friend_titles =
      Title
        .joins(:lists)
        .where(lists: { user: current_user.favorited_users})
        .distinct

    your_title =
      Title
        .joins(:lists)
        .where(lists: { name: "Watchlist", user: current_user})

    @toplist = (friend_titles & your_title).max_by(3){ |title| title.average_rating_title}
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      update_genres(@list)
      if params[:title_id].present?
        @title = Title.find(params[:title_id])
        ListItem.create(title: @title, list: @list, rank: @list.list_items.count + 1)
      end
      redirect_to @list, notice: 'List created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
    @list_items = @list.list_items.order(:rank)
    if @list.name == 'Watchlist'
      redirect_to @list, alert: 'The Watchlist cannot be renamed.'
    elsif @list.name == 'Ratings'
      redirect_to @list, alert: 'The Ratings list cannot be renamed.'
    else
      @list.genre_connections.build if @list.genre_connections.empty?
    end
  end

  def update
    @list = List.find(params[:id])
    if @list.name == 'Watchlist'
      redirect_to @list, alert: 'The Watchlist cannot be renamed.'
    elsif @list.name == 'Ratings'
      redirect_to @list, alert: 'The Ratings list cannot be renamed.'
    else
      begin
        ActiveRecord::Base.transaction do
          original_list = @list.list_items.order(:rank).to_a
          temp_list = original_list.dup

          @list.update!(list_update_params.except(:list_items_attributes))

          params[:list][:list_items_attributes].each do |id, attributes|
            item_to_move = temp_list.find { |item| item.id == id.to_i }
            new_position = attributes[:new_rank].to_i - 1
            old_position = attributes[:old_rank].to_i - 1

            if old_position != new_position
              temp_list.delete_at(old_position)
              temp_list.insert(new_position, item_to_move)
            end
          end

          temp_list.each_with_index do |item, index|
            item.update!(rank: index + 1)
          end

          update_genres(@list)

          redirect_to @list, notice: 'List was updated and genres were successfully linked.'
        end
      rescue => e
        @list.errors.add(:base, e.message)
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @list = List.find(params[:id])

    if @list.name == 'Watchlist'
      redirect_to lists_path, alert: 'The Watchlist cannot be deleted.'
    elsif @list.name == 'Ratings'
      redirect_to lists_path, alert: 'The Ratings list cannot be deleted.'
    else
      @list.destroy
      redirect_to lists_path, notice: 'List was deleted.', status: :see_other
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :description, :status, genre_ids: [])
  end

  def list_update_params
    params.require(:list).permit(:name, :description, :status, genre_connections_attributes: [:id, :genre_id, :_destroy], list_items_attributes: [:id, :old_rank, :new_rank], genre_ids: [])
  end

  def update_genres(list)
    list.genre_connections.destroy_all
    if params[:list][:genre_ids].present?
      params[:list][:genre_ids].reject(&:blank?).each do |genre_id|
        list.genre_connections.create!(genre_id: genre_id)
      end
    end
    flash[:notice] = "Genres were successfully linked with the list."
  end
end

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <div class="row">
    <div class="col-6">
      <%= f.input :name %>
      <%= f.input :status, collection: %w[Private Friend Public] %>
    </div>
    <div class="col-6">
      <%= f.input :description %>
    </div>
  </div>
  <%= f.submit %>
<% end %>

app/views/lists/_genre_connection_fields.html.erb
<div class="nested-fields">
  <%= f.input :genre_id, as: :select, collection: Genre.all.pluck(:name, :id), include_blank: "Select a genre" %>
  <%= link_to_remove_association "Remove", f %>
</div>

app/views/lists/edit.html.erb
<h1>Edit List</h1>
<%= simple_form_for(@list) do |f| %>
  <div class="row">
    <div class="col-6">
      <%= f.input :name %>
      <%= f.input :status, collection: %w[Private Friend Public] %>
    </div>
    <div class="col-6">
      <%= f.input :description %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <h3>Edit Genres</h3>
      <% 3.times do |index| %>
        <div class="form-group">
          <%= select_tag "list[genre_ids][]", options_for_select(Genre.all.pluck(:name, :id), @list.genre_connections[index]&.genre_id), include_blank: "Select a genre", class: 'form-control genre-select' %>
        </div>
      <% end %>
    </div>
  </div>

  <div>
    <h3>Edit Ranks</h3>
    <% if @list_items.any? %>
      <div class="container container-item-card">
        <% @list_items.each do |list_item| %>
          <div class="item-card">
            <%= render 'shared/item_card', title: list_item.title %>
            <label>Current Rank for <%= list_item.title.name %>: <%= list_item.rank %></label>
            <%= hidden_field_tag "list[list_items_attributes][#{list_item.id}][id]", list_item.id %>
            <%= hidden_field_tag "list[list_items_attributes][#{list_item.id}][old_rank]", list_item.rank %>
            <%= select_tag "list[list_items_attributes][#{list_item.id}][new_rank]", options_for_select((1..@list_items.count).to_a, list_item.rank), class: 'form-control' %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= f.submit "Update List", class: "btn btn-primary" %>
<% end %>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const genreSelects = document.querySelectorAll('.genre-select');

    function updateSelectOptions() {
      const selectedValues = Array.from(genreSelects)
        .map(select => select.value)
        .filter(value => value);

      genreSelects.forEach(select => {
        Array.from(select.options).forEach(option => {
          if (selectedValues.includes(option.value) && option.value !== select.value) {
            option.disabled = true;
          } else {
            option.disabled = false;
          }
        });
      });
    }

    genreSelects.forEach(select => {
      select.addEventListener('change', updateSelectOptions);
    });

    updateSelectOptions(); // Initial call to set the correct state
  });
</script>

app/views/lists/index.html.erb
<div class="container">
  <div class="text-center">
    <%= link_to 'Create New List', new_list_path, class: 'btn btn-create-list mb-4' %>
  </div>
</div>

<div class="container">
  <h1 class="page-heading mb-4">Genre</h2>

  <!-- Genre's Lists -->
  <div class="container-collection-genre"></div>
  <div id="carouselCoverCards" class="carousel slide">
    <div class="carousel-inner h-100">
      <% @genres.each_slice(4).each_with_index do |group, index| %>
        <div class="carousel-item <%= index == 0 ? "active" : "" %>">
          <div class="cover-card-list">
            <% group.each do |genre| %>
              <%= render 'shared/cover_card', genre: genre %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselCoverCards" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselCoverCards" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <!-- Members Lists -->
  <h1 class="page-heading mb-4 mt-4">Member's Lists</h2>

  <% @lists.reject{ |list| list.user == current_user || list.list_items.count < 1 }.each_slice(4).each_with_index do |group, index| %>
    <div class="collection-card-list">
      <% group.each do |list| %>
        <%= render 'shared/collection_card', list: list %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1 class="page-heading">New List</h1>
<div class="container">
  <%= render 'form', list: @list %>
</div>

app/views/lists/show.html.erb
<div>
  <!--Watchlist highlight-->
  <!-- <% if @list.name == "Watchlist" && current_user == @list.user %>
    <h2 class="text-center">
      Friend's <%= @toplist.size == 1 ? 'Favorite' : 'Favorites' %>
    </h2>
    <div class="container container-item-card-favorite">
      <% if @list_items.present? %>
        <% @toplist.each do |title| %>
          <div class="item-card-favorite">
            <%= render 'shared/item_card_favorite', title: title %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <%# do not display anything %>
  <% end %> -->

  <!--Header-->
  <div>
    <!--Title-->
    <% if @list.name == "Watchlist" && current_user == @list.user %>
    <h1 class="page-heading mb-1">My <%= @list.name %></h1>
    <% else %>
    <h1 class="page-heading mb-1"><%= @list.name %></h1>
    <% end %>

    <!--Status-->
    <!-- <div class="text-center">
      <p><%= @list.status.presence || "No status available" %></p>
    </div> -->

    <!--Created by-->
    <% unless @list.name == "Watchlist" %>
      <div class="created-by text-center mb-4">
        <span>List by:</span>
        <img src=
          <% if @list.user.profile_picture.attached? %>
            <%= url_for(@list.user.profile_picture) %>
          <% elsif @list.user.profile_picture_url.present? %>
            <%= @list.user.profile_picture_url %>
          <% else %>
            'https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg'
          <% end %> alt="<%= @list.user.first_name %>" class="avatar-listshow">
        <%= link_to @list.user.first_name, user_path(@list.user.username) %>
      </div>
    <% else %>
      <%# do not display anything%>
    <% end %>
  </div>

<!-- Description -->
<% unless @list.name == "Watchlist" %>
  <% if @list.description.present? %>
    <div class="container mb-3">
      <div class="row d-flex justify-content-center">
        <div class="col-6 mx-auto">
          <div class="text-center">
            <h4>Description</h4>
            <p><%= @list.description %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <%# do not display anything %>
<% end %>

  <!--Genre-->
  <div class="text-center">
    <div class="genre-buttons">
      <% @list.genres.each do |genre| %>
        <%= link_to genre.name, genre_path(genre.tmdb_id), class: "btn" %>
      <% end %>
    </div>
  </div>

  <!--List-->
  <div>
    <% if @list_items.any? %>
      <div class="container container-item-card-favorite">
        <% @list_items.each do |list_item| %>
          <div class="item-card">
            <%= render 'shared/item_card', title: list_item.title %>
            <% unless @list.name == "Watchlist" %>
              <% if @list.name != "Ratings" %>
                <p class="mb-1">Rank: <%= list_item.rank %></p>
            <% end %>
            <% review = list_item.title.reviews.find_by(user: @list.user) %>
            <% if review %>
              <div class="rating-info">
                <img src="
                  <% if review.user.profile_picture.attached? %>
                    <%= url_for(review.user.profile_picture) %>
                  <% elsif review.user.profile_picture_url.present? %>
                    <%= review.user.profile_picture_url %>
                  <% else %>
                    'https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg'
                  <% end %>" alt="<%= review.user.first_name %>" class="avatar-listshow">
                <span><i class="fas fa-star"></i><%= review.rating %>/10</span>
              </div>
              <!--<p><%= review.created_at.strftime("%B %d, %Y") %></p>-->
            <% else %>
              <div class="rating-info">
                <img src="
                  <% if @list.user.profile_picture.attached? %>
                    <%= url_for(@list.user.profile_picture) %>
                  <% elsif @list.user.profile_picture_url.present? %>
                    <%= @list.user.profile_picture_url %>
                  <% else %>
                    'https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg'
                  <% end %>" alt="<%= @list.user.first_name %>" class="avatar-listshow">
                <span>Rating: N/A</span>
              </div>
              <p>Date Reviewed: N/A</p>
            <% end %>
          <% end %>
          <% if current_user == @list.user %>
            <% unless @list.name == "Ratings" %>
              <%= link_to list_item_path(list_item), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-remove' do %>
                <i class="fa-solid fa-trash-can"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
  <div class="text-center">
  <p>No items in your Watchlist yet.</p>
  </div>
  <% end %>
</div>

<!--Return and Edit Buttons-->
<div class="text-center m-4">
  <%= link_to 'Back to Lists', lists_path, class: 'btn btn-secondary' %>
  <% if current_user == @list.user && @list.name != 'Watchlist' && @list.name != 'Ratings' %>
    <%= link_to 'Edit List', edit_list_path(@list), class: 'btn btn-primary' %>
    <%= link_to 'Delete List', @list, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this list?' }, class: 'btn btn-danger' %>
  <% end %>
</div>