config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"

  resources :genres, only: %i[index show]
  resources :lists, only: %i[show new create index edit update destroy] do
    resources :list_items, only: %i[create destroy update]
    resources :genre_connections, only: %i[create destroy update]
  end
  resources :titles, only: %i[index show new create] do
    resources :reviews, only: %i[create update destroy]
    resources :list_items, only: %i[create] do
      collection do
        post 'add_to_watchlist'
        post 'add_to_ratings_list'
      end
    end
  end
  resources :list_items, only: %i[new create destroy]

  get '/users/:username/followers', to: 'pages#followers', as: :followers
  get '/users/:username/following', to: 'users#following', as: :following
  get '/users/:username/follow', to: 'users#follow', as: :follow_user
  get '/users/:username/unfollow', to: 'users#unfollow', as: :unfollow_user

  get '/users/:username/edit', to: 'users#edit', as: :edit_user
  patch '/users/:username', to: 'users#update', as: :update_user

  get '/users/:username', to: 'users#show', as: :user
  get '/users/:username/lists', to: 'users#lists', as: 'user_lists'

  post 'add_to_watchlist', to: 'list_items#add_to_watchlist', as: :add_to_watchlist

  # Likes
  get '/reviews/:review/like_review', to: 'reviews#like_review', as: :like_review
  get '/reviews/:review/unlike_review', to: 'reviews#unlike_review', as: :unlike_review

  resources :people, only: %i[show]
  resources :services, only: %i[index show new create]
  resources :comments, only: [:create]

  get "up" => "rails/health#show", as: :rails_health_check

  get '/popular', to: 'titles#popular', as: :popular_titles
  get 'search', to: 'search#index', as: 'search'
  get 'movies', to: 'titles#movies', as: 'movies'
  get 'tv_shows', to: 'titles#tv_shows', as: 'tv_shows'
  get '/activity', to: 'pages#activity', as: :activity
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :streamings, dependent: :destroy
  # Although a title can have many streamings & services, the title ID is unique.
  # Specifying the distinct method will prevent the same title from being called
  # more than once when selecting titles with service or streaming joins
  has_many :titles, -> { distinct }, through: :streamings

  validates :name, presence: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @lists = current_user.lists
  end

  def create
    @list = List.find(params[:list_id])
    watchmode_api = WatchModeApi.new(ENV['WATCHMODE_API_KEY'])
    add_streaming_info_to_titles(@list.titles, watchmode_api)
    redirect_to services_path, notice: 'Streaming information added successfully'
  end

  private

  def add_streaming_info_to_titles(titles, watchmode_api)
    titles.each do |title|
      title_id = "#{title.media_type}-#{title.tmdb_id}"
      streaming_sources = watchmode_api.get_title_details(title_id, 'US')

      streaming_sources.select { |source| source['format'] == 'HD' }.each do |source|
        service = Service.find_or_create_by(name: source['name']) do |s|
          s.watchmode_id = source['id']
          s.logo_url = source['logo_100px']
        end

        Streaming.create!(
          url: source['web_url'],
          service: service,
          title: title,
          streaming_type: source['type']
        )
      end
    end
  end
end

app/views/services/index.html.erb
<h1>STREAMING SERVICES!</h1>
<br>

<div class="container d-flex gap-3 align-items-center flex-wrap">
  <% @services.each do |service| %>
    <% if service.streamings.count != 0 %>
      <div class="card" style="width: 100px;">
        <a href="<%= service_path(service) %>">
            <img src="<%= service.logo_url %>" class="card-img-top">
        </a>
      </div>
    <% end %>
  <% end %>
</div>

app/views/services/new.html.erb
<!-- app/views/services/new.html.erb -->
<h1>Add Streaming Information</h1>

<%= form_with(url: services_path, method: :post) do |form| %>
  <div class="form-group">
    <%= form.label :list_id, 'Select a List' %>
    <%= form.collection_select :list_id, @lists, :id, :name, include_blank: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.submit 'Add Streaming Information', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/services/results.html.erb
<!-- app/views/services/results.html.erb -->
<h1>Streaming Information Results</h1>

<% if @results.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Service</th>
        <th>URL</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each do |result| %>
        <tr>
          <td><%= result[:title] %></td>
          <td><%= result[:service] %></td>
          <td><%= link_to 'Watch', result[:url], target: '_blank' %></td>
          <td><%= result[:streaming_type] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No streaming information found for the selected list.</p>
<% end %>

app/views/services/show.html.erb
<img src="<%= @service.logo_url %>">
<div class="container d-flex gap-3 align-items-center flex-wrap">
  <%# For the current service instance, iterate over its associated titles %>
  <% @service.titles.each do |title| %>
    <%# For each title, display its poster %>
    <div class="card" style="width: 200px; height 400px;">
        <img src="<%= title.poster_url %>" class="card-img-top">
    </div>
    <%# Then, for each title display its available places to stream where the %>
    <%# streaming service is equal to the current service instance %>
    <% title.streamings.where(service: @service).each do |streaming| %>
      <%= link_to streaming.url, target: "_blank" do %>
        <button type="button" class="btn-primary">
        <%= display_streaming_type(streaming.streaming_type) %>
        </button>
      <% end %>
    <% end %>
  <% end %>
</div>