config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"

  resources :genres, only: %i[index show]
  resources :lists, only: %i[show new create index edit update destroy] do
    resources :list_items, only: %i[create destroy update]
    resources :genre_connections, only: %i[create destroy update]
  end
  resources :titles, only: %i[index show new create] do
    resources :reviews, only: %i[create update destroy]
    resources :list_items, only: %i[create] do
      collection do
        post 'add_to_watchlist'
        post 'add_to_ratings_list'
      end
    end
  end
  resources :list_items, only: %i[new create destroy]

  get '/users/:username/followers', to: 'pages#followers', as: :followers
  get '/users/:username/following', to: 'users#following', as: :following
  get '/users/:username/follow', to: 'users#follow', as: :follow_user
  get '/users/:username/unfollow', to: 'users#unfollow', as: :unfollow_user

  get '/users/:username/edit', to: 'users#edit', as: :edit_user
  patch '/users/:username', to: 'users#update', as: :update_user

  get '/users/:username', to: 'users#show', as: :user
  get '/users/:username/lists', to: 'users#lists', as: 'user_lists'

  post 'add_to_watchlist', to: 'list_items#add_to_watchlist', as: :add_to_watchlist

  # Likes
  get '/reviews/:review/like_review', to: 'reviews#like_review', as: :like_review
  get '/reviews/:review/unlike_review', to: 'reviews#unlike_review', as: :unlike_review

  resources :people, only: %i[show]
  resources :services, only: %i[index show new create]
  resources :comments, only: [:create]

  get "up" => "rails/health#show", as: :rails_health_check

  get '/popular', to: 'titles#popular', as: :popular_titles
  get 'search', to: 'search#index', as: 'search'
  get 'movies', to: 'titles#movies', as: 'movies'
  get 'tv_shows', to: 'titles#tv_shows', as: 'tv_shows'
  get '/activity', to: 'pages#activity', as: :activity
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :first_name, :last_name, presence: true

  has_many :follows, foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :follows, source: :followers
  has_many :followings, through: :follows, source: :followed

  has_many :lists, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :list_items, through: :lists, dependent: :destroy

  acts_as_favoritor
  acts_as_favoritable

  has_one_attached :profile_picture

  after_create_commit :create_watchlist

  def activity
    activities = lists + list_items + reviews
    activities.sort_by(&:created_at).reverse.first(10)
  end

  def friends_activity
    self.favorited_users.flat_map(&:activity).sort_by(&:created_at).reverse.first(10)
  end

  def all_activity
    (activity + friends_activity).sort_by(&:created_at).reverse
  end

  def find_user_watchlist
    self.lists.find_by(name: "Watchlist")
  end

  def create_watchlist
    self.lists.build(name: "Watchlist").save
  end
end

app/controllers/users/registrations_controller.rb
# app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    if @user.nil?
      redirect_to root_path, alert: "User not found."
    else
      @lists = @user.lists.order(:created_at)
      @follows = @user.follows
      @list_activity = @user.activity.reverse

      # Count movies and TV shows in the Ratings list
      ratings_list = @user.lists.find_by(name: 'Ratings')
      if ratings_list
        @movies_count = ratings_list.list_items.joins(:title).where(titles: { media_type: 'movie' }).count
        @tv_shows_count = ratings_list.list_items.joins(:title).where(titles: { media_type: 'tv' }).count
      else
        @movies_count = 0
        @tv_shows_count = 0
      end

    @my_top_movies = Title
    .joins(:reviews)
    .where(media_type: "movie", reviews: { user_id: @user.id })
    .order('reviews.rating DESC')

    @my_top_tv = Title
    .joins(:reviews)
    .where(media_type: "tv", reviews: { user_id: @user.id })
    .order('reviews.rating DESC')

    @my_top_genre = Genre
    .where.not(cover_url: nil)
    .where.not(name: ["Animation", "TV Movie", "Kids", "Documentary", "War"])
    .sample(12)

    @rated_titles = Title
      .joins(:reviews)
      .where(reviews: { user_id: @user.id })
      .select('titles.*, reviews.rating')
      .order('reviews.rating DESC')
      .limit(6)

      # Count lists excluding Watchlist and Ratings
      @lists_count = @user.lists.where.not(name: ['Watchlist', 'Ratings']).count
    end


  end

  def edit
    @user = User.find_by(username: params[:username])
    redirect_to root_path, alert: "You can only edit your own profile." unless @user == current_user
  end

  def update
    @user = User.find_by(username: params[:username])
    if @user.nil?
      redirect_to root_path, alert: "User not found."
    elsif @user.update(user_params)
      redirect_to user_path(@user.username), notice: "Profile updated successfully."
    else
      render :edit
    end

    @my_top_movies = Title
    .joins(:reviews)
    .where(media_type: "movie", reviews: { user_id: @user.id })
    .order('reviews.rating DESC')

    @my_top_tv = Title
    .joins(:reviews)
    .where(media_type: "tv", reviews: { user_id: @user.id })
    .order('reviews.rating DESC')

    @my_top_genre = Genre
    .where.not(cover_url: nil)
    .where.not(name: ["Animation", "TV Movie", "Kids", "Documentary", "War"])
    .sample(12)
  end

  def follow
    @user_to_follow = User.find_by(username: params[:username])
    current_user.favorite(@user_to_follow) if @user_to_follow
  end

  def unfollow
    @user_to_unfollow = User.find_by(username: params[:username])
    current_user.unfavorite(@user_to_unfollow) if @user_to_unfollow
  end

  def following
    @user = User.find_by(username: params[:username])
    if @user.nil?
      redirect_to root_path, alert: "User not found."
    else
      @following = @user.favorites_by_type('User').map(&:favoritable)
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :bio, :profile_picture)
  end
end

app/views/users/edit.html.erb
<%= form_with model: @user, url: update_user_path(@user.username), local: true, method: :patch, class: "form-horizontal" do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %> prevented this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name, class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control", placeholder: "Enter your first name" %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name, class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control", placeholder: "Enter your last name" %>
  </div>

  <div class="mb-3">
    <%= form.label :bio, class: "form-label" %>
    <%= form.text_area :bio, class: "form-control", placeholder: "Enter your bio" %>
  </div>

  <div class="mb-3">
    <%= form.label :profile_picture, "Upload Profile Picture", class: "form-label" %>
    <%= form.file_field :profile_picture, class: "form-control" %>
  </div>

  <%= form.submit "Update Profile", class: "btn btn-primary" %>
<% end %>

app/views/users/following.html.erb
<div class="container">
  <h1 class="page-heading">Following</h1>
  <div class="row">
    <% @following.each do |followed_user| %>
      <div class="col-md-4">
        <div class="card">
          <img src="<%= followed_user.profile_picture_url %>" class="card-img-top" alt="<%= followed_user.username %>">
          <div class="card-body">
            <h5 class="card-title"><%= link_to followed_user.username, user_path(followed_user.username) %></h5>
            <p class="card-text"><%= followed_user.bio %></p>
            <%= button_to (current_user.favorited?(followed_user) ? 'Unfollow' : 'Follow'), follow_user_path(followed_user.username), method: :post, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/lists.html.erb
<%# for future use see Vincent %>
<%# will display all the users lists %>

app/views/users/show.html.erb
<div class="container">
  <!--User Details-->
  <div class="container-user">
    <div class="user-details" data-controller="follow-toggle" data-follow-toggle-value="<%=@user.username %>">
      <div class="user-profile-details">
        <% if @user.profile_picture.attached? %>
          <%= image_tag @user.profile_picture, alt: @user.username, class: "avatar-user-page" %>
        <% elsif @user.profile_picture_url.present? %>
          <%= image_tag @user.profile_picture_url, alt: @user.username, class: "avatar-user-page" %>
        <% else %>
          <img class="avatar-user-page" src="https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg" alt="<%= @user.username %>'s Avatar">
        <% end %>
        <div class="user-profile-info">
          <h1 class="page-heading"><%= @user.first_name %></h1>
          <p class="user-profile-bio">@<%= @user.username %></p>
          <p class="user-profile-bio"><%= @user.bio.nil? ? "No biography" : @user.bio %></p>
          <% if @user != current_user %>
            <button class='btn btn-follow' data-action="click->follow-toggle#toggle_follow" data-follow-toggle-target="button"><%= current_user.favorited?(@user) ? "Unfollow" : "Follow" %></button>
          <% end %>
        </div>
      </div>
      <div class="user-status-details">
        <div class="user-status-info">
          <p>Followers</p>
          <%= link_to followers_path(@user.username) do %>
            <%= @user.favoritors_by_type('User').count == 0 ? 0 : @user.favoritors_by_type('User').count %>
          <% end %>
        </div>
        <div class="user-status-info">
          <p>Following</p>
          <%= link_to following_path(@user.username) do %>
            <%= @user.favorites_by_type('User').count == 0 ? 0 : @user.favorites_by_type('User').count %>
          <% end %>
        </div>
        <div class="user-status-info">
          <p>Movies</p>
          <%= @movies_count %>
        </div>
        <div class="user-status-info">
          <p>TV Shows</p>
          <%= @tv_shows_count %>
        </div>
        <div class="user-status-info">
          <p>Lists</p>
          <%= @lists_count %>
        </div>
      </div>
    </div>
  </div>
  <!-- User Top Rated Titles-->
  <% unless @user == current_user %>
    <h2 class="container page-heading"><%= @user.first_name %>'s Top Rated Titles</h2>
    <div class="container container-item-card">
      <% @rated_titles.each do |title| %>
        <%= render 'shared/item_card', title: title %>
      <% end %>
    </div>
  <% else %>
    <%# do not display anything%>
  <% end %>
  <!-- Following List -->
  <% unless @user != current_user %>
    <h2 class="container page-heading">My Friends</h2>
    <div id="carouselFollowing" class="carousel carousel-cards slide">
      <div class="carousel-inner carousel-card-inner">
        <% current_user.favorited_users.each_slice(7).each_with_index do |group, index| %>
          <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
            <div class="d-flex justify-content-center">
              <% group.each do |user| %>
                <%= link_to user_path(user.username) do %>
                  <div class="following-card">
                      <img class="avatar-following" src=
            <% if user.profile_picture.attached? %>
              <%= url_for(user.profile_picture) %>
            <% elsif user.profile_picture_url.present? %>
              <%= user.profile_picture_url %>
            <% else %>
              "https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg"
            <% end %> alt="<%= user.username %>'s Avatar" class="avatar-following">
                    <p><%= user.first_name %></p>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselFollowing" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselFollowing" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  <% end %>
  <!--User List-->
  <div class="row">
    <div class="col-7">
      <div class="container-collection container-collection-heading">
        <% if @user == current_user %>
          <h2 class="page-heading page-heading-list">My List</h2>
          <%= link_to 'New List', new_list_path, class: 'btn' %>
        <% else %>
          <h2 class="page-heading page-heading-list"><%= @user.first_name %>'s List</h2>
          <%= link_to 'New List', new_list_path, class: 'btn' %>
        <% end %>
      </div>
      <!-- My List Carousel -->
      <div id="carouselMyList" class="carousel carousel-cards slide">
        <div class="carousel-inner carousel-card-inner">
          <% @lists.each_slice(2).each_with_index do |group, index| %>
            <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
              <div class="collection-card-list">
                <% group.each do |list| %>
                  <%= render 'shared/collection_card', list: list %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselMyList" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselMyList" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <!-- My Fave Movie Carousel -->
      <div id="carouselMyFaveMovie" class="carousel carousel-cards slide">
        <% if @user == current_user %>
          <h2 class="container page-heading">My Favorite Movies</h2>
        <% else %>
          <h2 class="container page-heading"><%= @user.first_name %>'s Favorite Movies</h2>
        <% end %>
        <div class="carousel-inner carousel-card-inner">
          <% if @my_top_movies.present? %>
            <% @my_top_movies.each_slice(4).each_with_index do |group, index| %> <!-- Group movies by 4 -->
              <div class="carousel-item <%= index == 0 ? "active" : "" %>">
                <div class="item-card-list">
                  <% group.each do |title| %>
                    <%= render 'shared/item_card', title: title %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselMyFaveMovie" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselMyFaveMovie" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <!-- My Fave TV Show Carousel -->
      <div id="carouselMyTV" class="carousel carousel-cards slide">
        <% if @user == current_user %>
          <h2 class="container page-heading">My Favorite TV Shows</h2>
        <% else %>
          <h2 class="container page-heading"><%= @user.first_name %>'s Favorite TV Shows</h2>
        <% end %>
        <div class="carousel-inner carousel-card-inner">
          <% if @my_top_tv.present? %>
            <% @my_top_tv.each_slice(4).each_with_index do |group, index| %> <!-- Group movies by 4 -->
              <div class="carousel-item <%= index == 0 ? "active" : "" %>">
                <div class="item-card-list">
                  <% group.each do |title| %>
                    <%= render 'shared/item_card', title: title %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselMyTV" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselMyTV" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <!-- My Fave Genres -->
    </div>
    <!--Activity feed-->
    <div class="col">
      <% if @user == current_user %>
        <h2 class="container page-heading">My Activity</h2>
      <% else %>
        <h2 class="container page-heading"><%= @user.first_name %>'s Activity</h2>
      <% end %>
      <div class="container-activity-feed">
        <%= render 'shared/activity_feed', list_activity: @list_activity, title: "" %>
      </div>
    </div>
  </div>
</div>