config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"

  resources :genres, only: %i[index show]
  resources :lists, only: %i[show new create index edit update destroy] do
    resources :list_items, only: %i[create destroy update]
    resources :genre_connections, only: %i[create destroy update]
  end
  resources :titles, only: %i[index show new create] do
    resources :reviews, only: %i[create update destroy]
    resources :list_items, only: %i[create] do
      collection do
        post 'add_to_watchlist'
        post 'add_to_ratings_list'
      end
    end
  end
  resources :list_items, only: %i[new create destroy]

  get '/users/:username/followers', to: 'pages#followers', as: :followers
  get '/users/:username/following', to: 'users#following', as: :following
  get '/users/:username/follow', to: 'users#follow', as: :follow_user
  get '/users/:username/unfollow', to: 'users#unfollow', as: :unfollow_user

  get '/users/:username/edit', to: 'users#edit', as: :edit_user
  patch '/users/:username', to: 'users#update', as: :update_user

  get '/users/:username', to: 'users#show', as: :user
  get '/users/:username/lists', to: 'users#lists', as: 'user_lists'

  post 'add_to_watchlist', to: 'list_items#add_to_watchlist', as: :add_to_watchlist

  # Likes
  get '/reviews/:review/like_review', to: 'reviews#like_review', as: :like_review
  get '/reviews/:review/unlike_review', to: 'reviews#unlike_review', as: :unlike_review

  resources :people, only: %i[show]
  resources :services, only: %i[index show new create]
  resources :comments, only: [:create]

  get "up" => "rails/health#show", as: :rails_health_check

  get '/popular', to: 'titles#popular', as: :popular_titles
  get 'search', to: 'search#index', as: 'search'
  get 'movies', to: 'titles#movies', as: 'movies'
  get 'tv_shows', to: 'titles#tv_shows', as: 'tv_shows'
  get '/activity', to: 'pages#activity', as: :activity
end

app/views/shared/_activity_feed.html.erb
<% list_activity.each do |activity| %>
  <div class="activity-feed-item">
    <% case activity.class.name %>
    <% when 'Review' %>
      <%= render 'shared/activity_review', activity: activity %>
    <% when 'ListItem' %>
      <%= render 'shared/activity_list_item', activity: activity %>
      <%= render 'shared/activity_collection_card', activity: activity.list %>
    <% when 'List' %>
      <%= render 'shared/activity_collection_card', activity: activity %>
    <% end %>
  </div>
<% end %>

app/views/shared/_activity_list_item.html.erb
<div class="activity-feed-item-custom">
  <div class="activity-content-custom">
    <div class="activity-poster-custom">
      <%= link_to title_path(activity.title.id) do %>
        <img src="<%= activity.title.poster_url %>" alt="<%= activity.title.name %>">
      <% end %>
    </div>
    <div class="activity-details-custom">
      <div class="activity-header-custom">
        <div class="activity-title-year-custom">
          <span class="activity-username-custom">
            <%= link_to user_path(activity.user.username), class: 'custom-link' do %>
              <img src="
                <% if activity.user.profile_picture.attached? %>
                  <%= url_for(activity.user.profile_picture) %>
                <% elsif activity.user.profile_picture_url.present? %>
                  <%= activity.user.profile_picture_url %>
                <% else %>
                  https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg
                <% end %>" alt="<%= activity.user.username %>'s Avatar" class="avatar-custom">
              <%= activity.user.first_name %>
            <% end %>
          </span>
          <span class="activity-year-custom">
            Added: <%= link_to "#{activity.title.name}", title_path(activity.title.id), class: 'custom-link' %>
          </span>
          <span class="activity-year-custom">To the List: </span>
          <span class="activity-year-custom"><%= link_to activity.list.name, list_path(activity.list), class: 'custom-link' %></span>
        </div>
      </div>
      <div class="activity-time-custom">
        <%= activity_string(activity) %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_activity_review.html.erb
<div class="activity-feed-item-custom">
  <div class="activity-content-custom">
    <div class="activity-poster-custom">
      <%= link_to title_path(activity.title.id) do %>
        <img src="<%= activity.title.poster_url %>" alt="<%= activity.title.name %>">
      <% end %>
    </div>
    <div class="activity-details-custom" data-controller="review-likes" data-review-likes-review-id-value="<%= activity.id %>">
      <div class="activity-header-custom">
        <div class="activity-title-year-custom">
          <span class="activity-username-custom">
            <%= link_to user_path(activity.user.username), class: 'custom-link' do %>
              <img src="
                <% if activity.user.profile_picture.attached? %>
                  <%= url_for(activity.user.profile_picture) %>
                <% elsif activity.user.profile_picture_url.present? %>
                  <%= activity.user.profile_picture_url %>
                <% else %>
                  'https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg'
                <% end %>" alt="<%= activity.user.username %>'s Avatar" class="avatar-custom">
              <%= activity.user.first_name %>
            <% end %>
          </span>
        </div>
      </div>
      <div class="activity-title-year-custom">
        <span class="activity-year-custom">
          Reviewed: <%= link_to "#{activity.title.name}", title_path(activity.title.id), class: 'custom-link' %>
        </span>
      </div>
      <div class="activity-rating-custom">
        <%= '★' %> <%= activity.rating %>/10
      </div>
      <% if activity.comment.present? %>
        <div class="activity-comment-custom">
          <div>
            <i class="fa-solid fa-quote-left fa-quotes fa-2xs"></i>
            <%= activity.comment %> <i class="fa-solid fa-quote-right fa-quotes fa-2xs"></i>
          </div>
          <div class="activity-comment-like">
            <% if current_user.favorited?(activity) %>
              <i class="fa-solid fa-heart pointer"
          data-action="click->review-likes#toggle_likes"
                data-review-likes-target="heart"></i>
            <% else %>
              <i class="fa-regular fa-heart pointer"
          data-action="click->review-likes#toggle_likes"
                data-review-likes-target="heart"></i>
            <% end %>
            <span data-review-likes-target="counter"
      data-review-likes-likes-count-value="<%= activity.favoritors_by_type('User').count %>">
              <%= activity.favoritors_by_type('User').count %>
            </span>
          </div>
        </div>
      <% end %>
      <div class="activity-time-custom">
        <%= activity_string(activity) %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div id="carouselExample" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <% if current_page?(root_path) %>
      <% @genres.each_with_index do |genre, index| %>
        <div class="carousel-item <%= index == 0 ? "active" : "" %>" >
          <a href="<%= genre_path(genre.tmdb_id, cover_url: genre.cover_url, skip_update: true) %>" class="carousel-anchor">
            <img src="<%= genre.cover_url %>" class="carousel-item-img carousel-item-img-homepage" alt="Cover of <%= genre.name %>">
          </a>
          <div class="carousel-homepage-heading">
            <h1 class="carousel-homepage-title">KINOVIE</h1>
            <p class="carousel-homepage-subtitle">Find and recommend movies and TV shows to your friends!</p>
          </div>
        </div>
      <% end %>
      <!-- <div class="carousel-item">
      </div>
      <div class="carousel-item">
      </div> -->
    <% else %>
      <% @genres.each_with_index do |genre, index| %>
        <div class="carousel-item <%= index == 0 ? "active" : "" %>">
          <a href="<%= genre_path(genre.tmdb_id, cover_url: genre.cover_url, skip_update: true) %>">
            <img src="<%= genre.cover_url %>" class="carousel-item-img" alt="Cover of <%= genre.name %>">
          </a>
        </div>
      <% end %>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_collection_card.html.erb
<a href="<%= list_path(list) %>" class="card collection-card mb-3">
  <div class="collection-card-images">
    <% list.titles.each do |title| %>
      <% if list.titles.count == 1 %>
        <img src="<%= title.poster_url %>" alt="Poster of <%= title.name %>" class="collection-card-img collection-card-img-single">
      <% else %>
        <img src="<%= title.poster_url %>" alt="Poster of <%= title.name %>" class="collection-card-img">
      <% end %>
    <% end %>
  </div>
  <div class="card-body collection-card-body">
    <img class="avatar avatar-collection-card" src="
      <% if list.user.profile_picture.attached? %>
        <%= url_for(list.user.profile_picture) %>
      <% elsif list.user.profile_picture_url.present? %>
        <%= list.user.profile_picture_url %>
      <% else %>
        https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg
      <% end %>" alt="
      <% if list.user.username.nil? %>
        Your Avatar
      <% else %>
        <%= list.user.username %>'s Avatar
      <% end %>">
    <div class="collection-card-main-text">
      <h5 class="card-title collection-card-title"><%= list.name %></h5>
    </div>
    <div class="card-text collection-card-small-text">
      <div class="collection-card-film-number">
        <i class="fa-solid fa-film"></i>
        <span class="collection-card-subtitle"><%= list.titles.count %></span>
      </div>
      <p class="card-subtitle collection-card-username"><%= list.user.first_name %></p>
      <%# <div>
        <p>Icon 1</p>
        <p>Icon 2</p>
      </div> %>
    </div>
  </div>
</a>

app/views/shared/_cover_card.html.erb
<%= link_to genre_path(genre.tmdb_id) do %>
  <div class="card cover-card mb-3">
    <img src="<%= genre.cover_url %>" class="card-img-top cover-card-img-top" alt="Backdrop for <%= genre.name %>">
    <div class="card-body cover-card-body">
      <h5 class="card-title cover-card-title"><%= genre.name %></h5>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-light alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-light alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_item_card.html.erb
<div class="card item-card mb-3" data-add-to-watchlist-title-id-value="<%= title.id %>">
  <%= link_to title_path(title.id) do %>
    <img src="https://image.tmdb.org/t/p/w500<%= title.poster_url %>" alt="<%= title.name %>" class="card-img-top item-card-img-top">
  <% end %>
  <% if user_signed_in? && current_user.lists.any? %>
    <i class="fa-solid <%= title.in_watchlist?(current_user.find_user_watchlist) ? 'fa-check' : 'fa-plus' %> btn-add-watchlist"
      data-action="click->add-to-watchlist#addToWatchlist"
      data-add-to-watchlist-target="watchListBtn"
      data-id="<%= title.id %>"></i>
  <% end %>
  <div class="card-body item-card-body">
    <div class="">
      <h5 class="card-title item-card-title"><%= title.name %></h5>
      <div class="card-text item-card-small-texts">
        <div class="item-card-small-text">
          <% if title.media_type == 'tv' && title.start_year != title.end_year %>
            <span class="item-card-small-text-heading"><%= title.start_year %>
              <% if title.end_year %>
                - <%= title.end_year %>
              <% end %></span>
          <% else %>
            <span class="item-card-small-text-heading"><%= title.start_year %></span>
          <% end %>
          <span>·</span>
          <%= title.media_type == 'tv' ? 'TV Show' : title.media_type.capitalize %>
        </div>
      </div>
    </div>
    <div class="item-card-small-text item-card-small-text-rating">
      <% top_three_reviews(title.ordered_reviews).limit(1).each do |review| %>
        <% if review.present? %>
          <span class="item-card-small-text-rating-subheading">Recommended by</span>
          <%# <span class="item-card-small-text-rating-subheading">Rated by</span> %>
          <img class="avatar avatar-list-card" src=
            <% if review.user.profile_picture.attached? %>
              <%= url_for(review.user.profile_picture) %>
            <% elsif review.user.profile_picture_url.present? %>
              <%= review.user.profile_picture_url %>
            <% else %>
              'https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg'
            <% end %> alt="<%= review.user.username %>'s Avatar" class="avatar-nav">
          <span class="item-card-small-text-username"><%= review.user.first_name %></span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_item_card_favorite.html.erb
<div class="card item-card" data-add-to-watchlist-title-id-value="<%= title.id %>">
  <%= link_to title_path(title.id) do %>
    <img src="https://image.tmdb.org/t/p/w500<%= title.poster_url %>" alt="<%= title.name %>" class="card-img-top item-card-img-top">
  <% end %>
    <i class="fa-solid <%= title.in_watchlist?(current_user.find_user_watchlist) ? 'fa-check' : 'fa-plus' %> btn-add-watchlist"
      data-action="click->add-to-watchlist#addToWatchlist"
      data-add-to-watchlist-target="watchListBtn"
      data-id="<%= title.id %>"></i>
  <div class="card-body item-card-body">
    <div class="">
      <h5 class="card-title item-card-title"><%= title.name %></h5>
      <div class="card-text item-card-small-texts">
        <div class="item-card-small-text">
          <% if title.media_type == 'tv' && title.start_year != title.end_year %>
            <span class="item-card-small-text-heading"><%= title.start_year %>
              <% if title.end_year %>
                - <%= title.end_year %>
              <% end %></span>
          <% else %>
            <span class="item-card-small-text-heading"><%= title.start_year %></span>
          <% end %>
          <span>·</span>
          <%= title.media_type == 'tv' ? 'TV Show' : title.media_type.capitalize %>
        </div>
      </div>
    </div>
    <div class="item-card-small-text item-card-small-text-rating">
      <% top_three_reviews(title.ordered_reviews).limit(1).each do |review| %>
        <% if review.present? %>
          <span class="item-card-small-text-rating-subheading">Rated by</span>
          <img class="avatar avatar-list-card" src=<%= review.user.profile_picture_url || "https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg" %> alt="<%= review.user.username %>'s Avatar" class="avatar-nav">
          <span class="item-card-small-text-username"><%= review.user.first_name %></span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_item_description_card.html.erb
<div class="item-description-card">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" class="item-description-card-img"/>
  <div class="item-description-card-infos">
    <h2 class="item-description-card-title"><%= title.name %></h2>
    <div class="item-description-card-small-text">
      <p><%= title.start_year %></p>
      <% if title.end_year %>
         <p> - <%= title.end_year %></p>
      <% end %>
      <p>·</p>
      <p><%= title.media_type %></p>
      <p>·</p>
      <p>Duration</p>
    </div>
    <div class="item-description-card-main-text">Description</div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-kinovie">
  <div class="container-fluid">
    <div class="navbar-left">
      <%# APP LOGO %>
      <%= link_to root_path, class: "navbar-brand navbar-heading" do %>
        <i class="fa-solid fa-clapperboard"></i>
        <span>KINOVIE</span>
      <% end %>
      <%# LINKS %>
      <div class="navbar-links">
        <%= link_to "Movies", movies_path, class: "nav-link" %>
        <%= link_to "TV Shows", tv_shows_path, class: "nav-link" %>
        <%= link_to "Lists", lists_path, class: "nav-link" %>
      </div>
    </div>
    <%# SEARCH BAR %>
    <div class="search">
      <div class="search-form-control form-group">
        <%= form_with url: search_path, method: :get, local: true do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Search for Movies or TV Shows" %>
          <button type="submit" class="btn btn-search">
            <i class="fas fa-search"></i>
          </button>
        <% end %>
      </div>
    </div>
    <%# DROPDOWN %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <% watchlist = current_user.lists.find_by(name: 'Watchlist') %>
          <% if watchlist %>
            <li class="nav-item active"><%= link_to list_path(watchlist), class: "nav-link" do %>
                Watchlist <i class="fa-solid fa-film"></i>
                <span data-add-to-watchlist-target="counter">
                  <%= watchlist.list_items.count %>
                </span>
              <% end %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "#", class: "nav-link" do %>
              <i class="fa-regular fa-bell"></i>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src=
              <% if current_user.profile_picture.attached? %>
                <%= url_for(current_user.profile_picture) %>
              <% elsif current_user.profile_picture_url.present? %>
                <%= current_user.profile_picture_url %>
              <% else %>
                "https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg"
              <% end %> alt="<%= current_user.username || 'Your Avatar' %>"
            />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="<%= user_path(current_user.username) %>">My Profile</a>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item btn btn-user-logout" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_people_card.html.erb
<div class="card people-card mb-3">
  <img src="<%= person[:profile_path] %>" alt="<%= person[:name] %>" class="card-img-top people-card-img-top">
  <div class="card-body people-card-body">
    <h5 class="card-title people-card-title text-truncate"><%= person[:name] %></h5>
  </div>
</div>

app/views/shared/_review_card.html.erb
<div class="item-card item-review-card" data-controller="review-likes">
  <div class="item-review-user">
    <%= link_to user_path(review.user.username) do %>
      <img src="
        <% if review.user.profile_picture.attached? %>
          <%= url_for(review.user.profile_picture) %>
        <% elsif review.user.profile_picture_url.present? %>
          <%= review.user.profile_picture_url %>
        <% else %>
          'https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg'
        <% end %>" alt="<%= review.user.username %>'s Avatar" class="avatar-review-card">
    <% end %>
    <div class="item-review-user-rating">
      <p class="item-review-user-rating-text">
        <%= link_to user_path(review.user.username), class: 'item-review-username' do %>
          <strong><%= review.user.first_name %></strong>
        <% end %>
      </p>
      <p class="item-review-user-rating-text">
        <i class="fas fa-star"></i>
        <%= "#{review.rating}/10" %>
      </p>
    </div>
  </div>
  <div class="item-review-user-texts">
    <p class="item-review-user-review-text">
      <i class="fa-solid fa-quote-left fa-quotes fa-2xs"></i>
      <%= review.comment %>
      <i class="fa-solid fa-quote-right fa-quotes fa-2xs"></i>
    </p>
    <div class="item-review-heart">
      <% if current_user.favorited?(review) %>
        <i class="fa-solid fa-heart fa-lg"
           data-action="click->review-likes#toggle_likes"
           data-review-likes-target="heart"></i>
      <% else %>
        <i class="fa-regular fa-heart fa-lg"
           data-action="click->review-likes#toggle_likes"
           data-review-likes-target="heart"></i>
      <% end %>
      <div data-review-likes-target="counter"
           data-review-likes-likes-count-value="<%= review.favoritors_by_type('User').count %>"
           class="item-review-heart-counter">
        <%= review.favoritors_by_type('User').count %>
      </div>
    </div>
  </div>

  <!-- Comment Toggle Button -->
  <div class="text-right">
    <button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseComments<%= review.id %>" aria-expanded="false" aria-controls="collapseComments<%= review.id %>">
      <i class="fa-regular fa-comment"></i>
    </button>
  </div>

  <!-- Collapsible Comment Section -->
  <div class="collapse mt-2" id="collapseComments<%= review.id %>">
    <%= render 'comments/form', comment: @comment, commentable: review %>
    <% review.comments.each do |comment| %>
      <p><%= comment.content %></p>
    <% end %>
  </div>

  <% if review.user == current_user %>
    <%= link_to title_review_path(@title, review), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-remove' do %>
      Delete Review
    <% end %>
  <% end %>
</div>

app/views/shared/_streaming_service_card.html.erb
<div class="card cover-card text-bg-dark">
  <img src="https://cdn.pixabay.com/photo/2018/05/01/07/52/tuscany-3364921_1280.jpg" class="card-img cover-card-img" alt="...">
  <div class="card-img-overlay cover-card-img-overlay">
    <h5 class="card-title cover-card-title">Card title</h5>
  </div>
</div>